# Generated by Django 3.2 on 2021-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='contact_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
