# Generated by Django 3.2 on 2021-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_useraccount_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='contact_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
