# Generated by Django 3.2 on 2021-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_useraccount_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
