# Generated by Django 3.2 on 2021-05-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_room_desc_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
